# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R52YrF_yfy8iXNauKD9necon1t2TjbCs
"""

from cgitb import text
import random as rnd
import math as m
import numpy as np
import statistics as stat
import scipy.stats as stat2


lda = 3 # llegadas por segundo
tllegadas = []
tintrallegadas = []
T = 10000.0 # tiempo total de llegada
L = 100000 # llegadas máximas
I = 0 # llegadas
t = 0.0 # tiempo evento actual
while t < T and I <= L:
    x = - ((1/lda)*m.log(rnd.random()))
    t = t + x
    #print("Llegada N° {} - tiempo: {}".format(I+1, t))
    I += 1
    tllegadas.append(t)
    tintrallegadas.append(x)

print(tllegadas)
print(len(tllegadas))
media = stat.mean(tintrallegadas)
print("El promedio de tiempos de llegada es {}, el inverso es {}".format(media, 1/media))

categ = round(1 + (m.log(len(tintrallegadas))/(m.log(2))))
print("{} categorias".format(categ))

maximo = max(tintrallegadas)
print("{} máximo".format(maximo))

obs, bins = np.histogram(tintrallegadas, categ)

print(obs)
print(bins)
probs = 1- np.exp(-lda*bins)
print(probs)
P = []

for k in range(1,categ+1):
    cc = probs[k] - probs[k-1]
    P.append(cc)

print(P)
print(len(P))

PROBS = np.array(P)
esp = PROBS * len(tintrallegadas)

print(esp)

print(sum(esp))
print(sum(obs))

est_chi = 0

for k in range(categ):
    est_chi = est_chi + ((obs[k] - esp[k])**2)/esp[k]

result = stat2.chisquare(obs, esp, categ - 1, axis = None )
print(result.statistic)
print(est_chi)
print(stat2.chi2.cdf(est_chi, categ - 1))
print(stat2.chi2.cdf(result.statistic, categ - 1))






# nllegadas = []
# t = 0
# TE = int(T)
# while( t < TE):
#     i = 0
#     p = m.exp(-lda)
#     F = p
#     parada = False
#     while not (parada):
#         U = rnd.random()
#         if (U < F):
#             x = i 
#             parada = True
#         else :
#             p = (lda * p)/(i + 1)
#             F = F + p
#             i += 1
#     #print(x)
#     nllegadas.append(x)
#     t += 1
# print(len(nllegadas))
# print(nllegadas)
# media = stat.mean(nllegadas)
# print("El promedio de llegadas en {} periodos de tiempo es: {}".format(T, media))